# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/valentinod3m0n/Code/list-c-

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/valentinod3m0n/Code/list-c-

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/valentinod3m0n/Code/list-c-/CMakeFiles /home/valentinod3m0n/Code/list-c-/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/valentinod3m0n/Code/list-c-/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named list

# Build rule for target.
list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 list
.PHONY : list

# fast build rule for target.
list/fast:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/build
.PHONY : list/fast

list.o: list.cc.o

.PHONY : list.o

# target to build an object file
list.cc.o:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/list.cc.o
.PHONY : list.cc.o

list.i: list.cc.i

.PHONY : list.i

# target to preprocess a source file
list.cc.i:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/list.cc.i
.PHONY : list.cc.i

list.s: list.cc.s

.PHONY : list.s

# target to generate assembly for a file
list.cc.s:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/list.cc.s
.PHONY : list.cc.s

list_node.o: list_node.cc.o

.PHONY : list_node.o

# target to build an object file
list_node.cc.o:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/list_node.cc.o
.PHONY : list_node.cc.o

list_node.i: list_node.cc.i

.PHONY : list_node.i

# target to preprocess a source file
list_node.cc.i:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/list_node.cc.i
.PHONY : list_node.cc.i

list_node.s: list_node.cc.s

.PHONY : list_node.s

# target to generate assembly for a file
list_node.cc.s:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/list_node.cc.s
.PHONY : list_node.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/list.dir/build.make CMakeFiles/list.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... list"
	@echo "... edit_cache"
	@echo "... list.o"
	@echo "... list.i"
	@echo "... list.s"
	@echo "... list_node.o"
	@echo "... list_node.i"
	@echo "... list_node.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

